name: Deploy React App to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      REACT_APP_API_URL: ${{ vars.REACT_APP_API_URL }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # - name: Run ESLint Fix
      #   run: npx eslint . --fix

      - name: Install Dependencies
        run: npm install --force

      - name: Build Project
        run: CI=false npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
